import sys
import os
myDir = os.getcwd()
sys.path.append(myDir)

from PyQt5 import QtCore, QtGui, QtWidgets

from Controllers.CreatePersonController import CreatePersonController

class Ui_Create_data(object):
    def __init__(self):
        self.create_person_controller=CreatePersonController(self)

    def setupUi(self, Create_data):
        Create_data.setObjectName("Create_data")
        Create_data.resize(435, 504)
        Create_data.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_10 = QtWidgets.QLabel(Create_data)
        self.label_10.setGeometry(QtCore.QRect(90, 10, 361, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(32, 74, 135))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 239, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(119, 119, 119))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 239, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 74, 135))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 239, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(119, 119, 119))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 239, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(119, 119, 119))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 239, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(119, 119, 119))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(119, 119, 119))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(119, 119, 119))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 239, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 239, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 239, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.label_10.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("TeX Gyre Termes Math")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setTextFormat(QtCore.Qt.RichText)
        self.label_10.setObjectName("label_10")
        self.btn_Ok = QtWidgets.QPushButton(Create_data)
        self.btn_Ok.setGeometry(QtCore.QRect(150, 460, 141, 41))
        self.btn_Ok.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_Ok.setObjectName("btn_Ok")
        self.widget = QtWidgets.QWidget(Create_data)
        self.widget.setGeometry(QtCore.QRect(40, 70, 371, 381))
        self.widget.setObjectName("widget")
        self.formLayout = QtWidgets.QFormLayout(self.widget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.lbl_ID = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.lbl_ID.setFont(font)
        self.lbl_ID.setObjectName("lbl_ID")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_ID)
        self.lineEdit_ID = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(14)
        font.setItalic(True)
        self.lineEdit_ID.setFont(font)
        self.lineEdit_ID.setObjectName("lineEdit_ID")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_ID)
        self.lbl_Nombre = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.lbl_Nombre.setFont(font)
        self.lbl_Nombre.setObjectName("lbl_Nombre")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lbl_Nombre)
        self.lineEdit_Nombre = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(14)
        font.setItalic(True)
        self.lineEdit_Nombre.setFont(font)
        self.lineEdit_Nombre.setObjectName("lineEdit_Nombre")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_Nombre)
        self.lbl_Apellido = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.lbl_Apellido.setFont(font)
        self.lbl_Apellido.setObjectName("lbl_Apellido")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lbl_Apellido)
        self.lineEdit_Apellido = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(14)
        font.setItalic(True)
        self.lineEdit_Apellido.setFont(font)
        self.lineEdit_Apellido.setObjectName("lineEdit_Apellido")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_Apellido)
        self.lbl_Edad = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.lbl_Edad.setFont(font)
        self.lbl_Edad.setObjectName("lbl_Edad")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lbl_Edad)
        self.lineEdit_Edad = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(14)
        font.setItalic(True)
        self.lineEdit_Edad.setFont(font)
        self.lineEdit_Edad.setObjectName("lineEdit_Edad")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_Edad)
        self.lbl_Ocupacin = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.lbl_Ocupacin.setFont(font)
        self.lbl_Ocupacin.setObjectName("lbl_Ocupacin")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lbl_Ocupacin)
        self.lineEdit_Ocupacion = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(14)
        font.setItalic(True)
        self.lineEdit_Ocupacion.setFont(font)
        self.lineEdit_Ocupacion.setObjectName("lineEdit_Ocupacion")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_Ocupacion)
        self.lbl_Telefono = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.lbl_Telefono.setFont(font)
        self.lbl_Telefono.setObjectName("lbl_Telefono")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.lbl_Telefono)
        self.lineEdit_telefono = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(14)
        font.setItalic(True)
        self.lineEdit_telefono.setFont(font)
        self.lineEdit_telefono.setObjectName("lineEdit_telefono")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.lineEdit_telefono)
        self.lbl_Direccion = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.lbl_Direccion.setFont(font)
        self.lbl_Direccion.setObjectName("lbl_Direccion")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.lbl_Direccion)
        self.lineEdit_Direccion = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(14)
        font.setItalic(True)
        self.lineEdit_Direccion.setFont(font)
        self.lineEdit_Direccion.setObjectName("lineEdit_Direccion")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.lineEdit_Direccion)
        self.lbl_FechaDeNacimiento = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.lbl_FechaDeNacimiento.setFont(font)
        self.lbl_FechaDeNacimiento.setObjectName("lbl_FechaDeNacimiento")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.lbl_FechaDeNacimiento)
        self.lbl_EstadoCivil = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.lbl_EstadoCivil.setFont(font)
        self.lbl_EstadoCivil.setObjectName("lbl_EstadoCivil")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.lbl_EstadoCivil)
        self.lineEdit_EstadoCivil = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(14)
        font.setItalic(True)
        self.lineEdit_EstadoCivil.setFont(font)
        self.lineEdit_EstadoCivil.setObjectName("lineEdit_EstadoCivil")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.lineEdit_EstadoCivil)
        self.lbl_Observaciones = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.lbl_Observaciones.setFont(font)
        self.lbl_Observaciones.setObjectName("lbl_Observaciones")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.lbl_Observaciones)
        self.lineEdit_Observaciones = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(14)
        font.setItalic(True)
        self.lineEdit_Observaciones.setFont(font)
        self.lineEdit_Observaciones.setObjectName("lineEdit_Observaciones")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.lineEdit_Observaciones)
        self.lineEdit_FechaDeNacimiento = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(14)
        font.setItalic(True)
        self.lineEdit_FechaDeNacimiento.setFont(font)
        self.lineEdit_FechaDeNacimiento.setObjectName("lineEdit_FechaDeNacimiento")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.lineEdit_FechaDeNacimiento)

        self.retranslateUi(Create_data)
        QtCore.QMetaObject.connectSlotsByName(Create_data)

        #----------------------------------Evento-------------------
        self.x=self.btn_Ok.clicked.connect(lambda:self.create_person_controller.createPerson(self.lineEdit_ID.text(),self.lineEdit_Nombre.text(),self.lineEdit_Apellido.text(),self.lineEdit_Edad.text(),self.lineEdit_Ocupacion.text(),self.lineEdit_telefono.text(),self.lineEdit_Direccion.text(),self.lineEdit_FechaDeNacimiento.text(),self.lineEdit_EstadoCivil.text(),self.lineEdit_Observaciones.text(),Create_data))
        #+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++



    def retranslateUi(self, Create_data):
        _translate = QtCore.QCoreApplication.translate
        Create_data.setWindowTitle(_translate("Create_data", "Form"))
        self.label_10.setText(_translate("Create_data", "AÑADIR INFORMACIÓN"))
        self.btn_Ok.setText(_translate("Create_data", "OK"))
        self.lbl_ID.setText(_translate("Create_data", "ID"))
        self.lineEdit_ID.setPlaceholderText(_translate("Create_data", "ID"))
        self.lbl_Nombre.setText(_translate("Create_data", "Nombre"))
        self.lineEdit_Nombre.setPlaceholderText(_translate("Create_data", "Nombre"))
        self.lbl_Apellido.setText(_translate("Create_data", "Apellido"))
        self.lineEdit_Apellido.setPlaceholderText(_translate("Create_data", "Apellido"))
        self.lbl_Edad.setText(_translate("Create_data", "Edad"))
        self.lineEdit_Edad.setPlaceholderText(_translate("Create_data", "Edad"))
        self.lbl_Ocupacin.setText(_translate("Create_data", "Ocupación"))
        self.lineEdit_Ocupacion.setPlaceholderText(_translate("Create_data", "Ocupacion"))
        self.lbl_Telefono.setText(_translate("Create_data", "Teléfono"))
        self.lineEdit_telefono.setPlaceholderText(_translate("Create_data", "Telefono"))
        self.lbl_Direccion.setText(_translate("Create_data", "Dirección"))
        self.lineEdit_Direccion.setPlaceholderText(_translate("Create_data", "Direccion"))
        self.lbl_FechaDeNacimiento.setText(_translate("Create_data", "Fecha de nacimiento"))
        self.lbl_EstadoCivil.setText(_translate("Create_data", "Estado civil"))
        self.lineEdit_EstadoCivil.setPlaceholderText(_translate("Create_data", "Estado Civil"))
        self.lbl_Observaciones.setText(_translate("Create_data", "Observaciones"))
        self.lineEdit_Observaciones.setPlaceholderText(_translate("Create_data", "Observaciones"))
        self.lineEdit_FechaDeNacimiento.setPlaceholderText(_translate("Create_data", "Fecha de Nacimiento"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Create_data = QtWidgets.QWidget()
    ui = Ui_Create_data()
    ui.setupUi(Create_data)
    Create_data.show()
    sys.exit(app.exec_())
